events {}

http {

    upstream auth_service {
        server auth-service:8000;
    }

    upstream chat_service {
        server chat-service:8000;
    }

    upstream resume_service {
        server resume-service:8000;
    }

    upstream embedding_service {
        server embedding-service:8000;
    }

    upstream notification_service {
        server notification-service:8000;
    }

    server {

        listen 80;

        location /api/auth/ {
            rewrite ^/api/auth/(.*)$ /$1 break;
            proxy_pass http://auth_service;
        }

        location /api/chat/ {
            rewrite ^/api/chat/(.*)$ /$1 break;
            proxy_pass http://chat_service;
        }

        location /api/resume/ {
            rewrite ^/api/resume/(.*)$ /$1 break;
            proxy_pass http://resume_service;
        }

        location /api/embed/ {
            rewrite ^/api/embed/(.*)$ /$1 break;
            proxy_pass http://embedding_service;
        }

        location /api/notify/ {
            rewrite ^/api/notify/(.*)$ /$1 break;
            proxy_pass http://notification_service;
        }

    }
}